
################################################################################

FROM --platform={{targetplatform}} {{distro}}:{{version}} as rootfs

{% include "Dockerfile.alpine.packages" %}
{% include "Dockerfile.common.files" %}
{% include "Dockerfile.common.users" %}
{% include "Dockerfile.common.commands" %}

COPY artifacts /

################################################################################
