FROM debian:bullseye-slim as tools
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y automake build-essential git libconfuse-dev libtool pkg-config
RUN git clone https://github.com/pengutronix/genimage.git
WORKDIR genimage
RUN ./autogen.sh
RUN ./configure
RUN make
RUN make install
RUN apt-get install -y genext2fs qemu-utils
