################################################################################

{% include "docker/Dockerfile.common.tools" %}

################################################################################

FROM tools as build
COPY --from=rootfs / /build/root
COPY {{ variant }}.cfg /build/
WORKDIR /build
RUN genimage --config {{ variant }}.cfg /build

################################################################################
