FROM debian:{{version}}
ARG DEBIAN_FRONTEND=noninteractive
ENTRYPOINT ["sh"]
RUN apt-get update
RUN apt-get install -y automake bc bison flex libpython3-dev libssl-dev libtool lzop make mtools pkg-config python3 python3-distutils python3-pkg-resources swig
RUN apt-get install -y build-essential
RUN apt-get install -y crossbuild-essential-armhf
RUN apt-get install -y crossbuild-essential-arm64
